name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v7.0.1
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      # actions/setup-python@v7.0.0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: '3.12'

      - name: Install linters
        run: pip install hadolint-py==2.15.1.2 "yamllint==1.35.1"

      - name: Lint YAML
        run: yamllint .tekton files rpms.in.yaml .github/workflows

      - name: Lint Containerfile
        run: hadolint --failure-threshold error Containerfile
